/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddStepsRouteImport } from './routes/add-steps'
import { Route as IndexRouteImport } from './routes/index'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddStepsRoute = AddStepsRouteImport.update({
  id: '/add-steps',
  path: '/add-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-steps': typeof AddStepsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-steps': typeof AddStepsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-steps': typeof AddStepsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-steps' | '/auth' | '/join'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-steps' | '/auth' | '/join'
  id: '__root__' | '/' | '/add-steps' | '/auth' | '/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddStepsRoute: typeof AddStepsRoute
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-steps': {
      id: '/add-steps'
      path: '/add-steps'
      fullPath: '/add-steps'
      preLoaderRoute: typeof AddStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddStepsRoute: AddStepsRoute,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
