/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddStepsRouteImport } from './routes/add-steps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsStoreIdRouteImport } from './routes/restaurants.$storeId'

const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddStepsRoute = AddStepsRouteImport.update({
  id: '/add-steps',
  path: '/add-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsStoreIdRoute = RestaurantsStoreIdRouteImport.update({
  id: '/restaurants/$storeId',
  path: '/restaurants/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-steps': typeof AddStepsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/manager': typeof ManagerRoute
  '/market': typeof MarketRoute
  '/restaurants/$storeId': typeof RestaurantsStoreIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-steps': typeof AddStepsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/manager': typeof ManagerRoute
  '/market': typeof MarketRoute
  '/restaurants/$storeId': typeof RestaurantsStoreIdRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-steps': typeof AddStepsRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/manager': typeof ManagerRoute
  '/market': typeof MarketRoute
  '/restaurants/$storeId': typeof RestaurantsStoreIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-steps'
    | '/auth'
    | '/join'
    | '/leaderboard'
    | '/manager'
    | '/market'
    | '/restaurants/$storeId'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-steps'
    | '/auth'
    | '/join'
    | '/leaderboard'
    | '/manager'
    | '/market'
    | '/restaurants/$storeId'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/add-steps'
    | '/auth'
    | '/join'
    | '/leaderboard'
    | '/manager'
    | '/market'
    | '/restaurants/$storeId'
    | '/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddStepsRoute: typeof AddStepsRoute
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ManagerRoute: typeof ManagerRoute
  MarketRoute: typeof MarketRoute
  RestaurantsStoreIdRoute: typeof RestaurantsStoreIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-steps': {
      id: '/add-steps'
      path: '/add-steps'
      fullPath: '/add-steps'
      preLoaderRoute: typeof AddStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$storeId': {
      id: '/restaurants/$storeId'
      path: '/restaurants/$storeId'
      fullPath: '/restaurants/$storeId'
      preLoaderRoute: typeof RestaurantsStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddStepsRoute: AddStepsRoute,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  ManagerRoute: ManagerRoute,
  MarketRoute: MarketRoute,
  RestaurantsStoreIdRoute: RestaurantsStoreIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
